# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DI_seqence_gen.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog_sequence_gen(object):
    def setupUi(self, Dialog_sequence_gen):
        Dialog_sequence_gen.setObjectName(_fromUtf8("Dialog_sequence_gen"))
        Dialog_sequence_gen.resize(640, 480)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog_sequence_gen)
        self.buttonBox.setGeometry(QtCore.QRect(10, 440, 621, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.layoutWidget = QtGui.QWidget(Dialog_sequence_gen)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 16, 260, 217))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_type = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_type.setMargin(1)
        self.verticalLayout_type.setSpacing(3)
        self.verticalLayout_type.setObjectName(_fromUtf8("verticalLayout_type"))
        self.label_seq_gen = QtGui.QLabel(self.layoutWidget)
        self.label_seq_gen.setObjectName(_fromUtf8("label_seq_gen"))
        self.verticalLayout_type.addWidget(self.label_seq_gen)
        self.listWidget_types = QtGui.QListWidget(self.layoutWidget)
        self.listWidget_types.setObjectName(_fromUtf8("listWidget_types"))
        self.verticalLayout_type.addWidget(self.listWidget_types)
        self.pushButton_open_existing_seq = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_open_existing_seq.setObjectName(_fromUtf8("pushButton_open_existing_seq"))
        self.verticalLayout_type.addWidget(self.pushButton_open_existing_seq)
        self.pushButton_reset_seq_gen = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_reset_seq_gen.setObjectName(_fromUtf8("pushButton_reset_seq_gen"))
        self.verticalLayout_type.addWidget(self.pushButton_reset_seq_gen)
        self.layoutWidget_4 = QtGui.QWidget(Dialog_sequence_gen)
        self.layoutWidget_4.setGeometry(QtCore.QRect(20, 310, 461, 51))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.horizontalLayout_LOAD = QtGui.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_LOAD.setObjectName(_fromUtf8("horizontalLayout_LOAD"))
        self.verticalLayout_load_min = QtGui.QVBoxLayout()
        self.verticalLayout_load_min.setMargin(1)
        self.verticalLayout_load_min.setSpacing(3)
        self.verticalLayout_load_min.setObjectName(_fromUtf8("verticalLayout_load_min"))
        self.label_load_min = QtGui.QLabel(self.layoutWidget_4)
        self.label_load_min.setObjectName(_fromUtf8("label_load_min"))
        self.verticalLayout_load_min.addWidget(self.label_load_min)
        self.doubleSpinBox_load_min = QtGui.QDoubleSpinBox(self.layoutWidget_4)
        self.doubleSpinBox_load_min.setEnabled(False)
        self.doubleSpinBox_load_min.setFrame(True)
        self.doubleSpinBox_load_min.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_load_min.setDecimals(1)
        self.doubleSpinBox_load_min.setSingleStep(0.0)
        self.doubleSpinBox_load_min.setProperty("value", 10.0)
        self.doubleSpinBox_load_min.setObjectName(_fromUtf8("doubleSpinBox_load_min"))
        self.verticalLayout_load_min.addWidget(self.doubleSpinBox_load_min)
        self.horizontalLayout_LOAD.addLayout(self.verticalLayout_load_min)
        self.verticalLayout_load_max = QtGui.QVBoxLayout()
        self.verticalLayout_load_max.setMargin(1)
        self.verticalLayout_load_max.setSpacing(3)
        self.verticalLayout_load_max.setObjectName(_fromUtf8("verticalLayout_load_max"))
        self.label_load_max = QtGui.QLabel(self.layoutWidget_4)
        self.label_load_max.setObjectName(_fromUtf8("label_load_max"))
        self.verticalLayout_load_max.addWidget(self.label_load_max)
        self.doubleSpinBox_load_max = QtGui.QDoubleSpinBox(self.layoutWidget_4)
        self.doubleSpinBox_load_max.setEnabled(False)
        self.doubleSpinBox_load_max.setFrame(True)
        self.doubleSpinBox_load_max.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_load_max.setDecimals(1)
        self.doubleSpinBox_load_max.setProperty("value", 90.0)
        self.doubleSpinBox_load_max.setObjectName(_fromUtf8("doubleSpinBox_load_max"))
        self.verticalLayout_load_max.addWidget(self.doubleSpinBox_load_max)
        self.horizontalLayout_LOAD.addLayout(self.verticalLayout_load_max)
        self.verticalLayout_load_step = QtGui.QVBoxLayout()
        self.verticalLayout_load_step.setMargin(1)
        self.verticalLayout_load_step.setSpacing(3)
        self.verticalLayout_load_step.setObjectName(_fromUtf8("verticalLayout_load_step"))
        self.label_load_step = QtGui.QLabel(self.layoutWidget_4)
        self.label_load_step.setObjectName(_fromUtf8("label_load_step"))
        self.verticalLayout_load_step.addWidget(self.label_load_step)
        self.doubleSpinBox_load_step = QtGui.QDoubleSpinBox(self.layoutWidget_4)
        self.doubleSpinBox_load_step.setEnabled(False)
        self.doubleSpinBox_load_step.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_load_step.setDecimals(1)
        self.doubleSpinBox_load_step.setObjectName(_fromUtf8("doubleSpinBox_load_step"))
        self.verticalLayout_load_step.addWidget(self.doubleSpinBox_load_step)
        self.horizontalLayout_LOAD.addLayout(self.verticalLayout_load_step)
        self.verticalLayout_rpm_direction_2 = QtGui.QVBoxLayout()
        self.verticalLayout_rpm_direction_2.setMargin(1)
        self.verticalLayout_rpm_direction_2.setSpacing(3)
        self.verticalLayout_rpm_direction_2.setObjectName(_fromUtf8("verticalLayout_rpm_direction_2"))
        self.label_load_direction = QtGui.QLabel(self.layoutWidget_4)
        self.label_load_direction.setObjectName(_fromUtf8("label_load_direction"))
        self.verticalLayout_rpm_direction_2.addWidget(self.label_load_direction)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.checkBox_load_dir_TD = QtGui.QCheckBox(self.layoutWidget_4)
        self.checkBox_load_dir_TD.setEnabled(False)
        self.checkBox_load_dir_TD.setAutoExclusive(True)
        self.checkBox_load_dir_TD.setObjectName(_fromUtf8("checkBox_load_dir_TD"))
        self.horizontalLayout_4.addWidget(self.checkBox_load_dir_TD)
        self.checkBox_load_dir_BU = QtGui.QCheckBox(self.layoutWidget_4)
        self.checkBox_load_dir_BU.setEnabled(False)
        self.checkBox_load_dir_BU.setChecked(True)
        self.checkBox_load_dir_BU.setAutoExclusive(True)
        self.checkBox_load_dir_BU.setObjectName(_fromUtf8("checkBox_load_dir_BU"))
        self.horizontalLayout_4.addWidget(self.checkBox_load_dir_BU)
        self.verticalLayout_rpm_direction_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_LOAD.addLayout(self.verticalLayout_rpm_direction_2)
        self.widget = QtGui.QWidget(Dialog_sequence_gen)
        self.widget.setGeometry(QtCore.QRect(300, 20, 331, 52))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_seq_name = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_seq_name.setMargin(1)
        self.verticalLayout_seq_name.setSpacing(3)
        self.verticalLayout_seq_name.setObjectName(_fromUtf8("verticalLayout_seq_name"))
        self.label_gen_seq_name = QtGui.QLabel(self.widget)
        self.label_gen_seq_name.setObjectName(_fromUtf8("label_gen_seq_name"))
        self.verticalLayout_seq_name.addWidget(self.label_gen_seq_name)
        self.lineEdit_gen_seq_name = QtGui.QLineEdit(self.widget)
        self.lineEdit_gen_seq_name.setEnabled(False)
        self.lineEdit_gen_seq_name.setMaxLength(127)
        self.lineEdit_gen_seq_name.setObjectName(_fromUtf8("lineEdit_gen_seq_name"))
        self.verticalLayout_seq_name.addWidget(self.lineEdit_gen_seq_name)
        self.widget1 = QtGui.QWidget(Dialog_sequence_gen)
        self.widget1.setGeometry(QtCore.QRect(290, 120, 341, 53))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.horizontalLayout_timing = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout_timing.setMargin(2)
        self.horizontalLayout_timing.setObjectName(_fromUtf8("horizontalLayout_timing"))
        self.verticalLayout_time_slope = QtGui.QVBoxLayout()
        self.verticalLayout_time_slope.setMargin(1)
        self.verticalLayout_time_slope.setSpacing(3)
        self.verticalLayout_time_slope.setObjectName(_fromUtf8("verticalLayout_time_slope"))
        self.label_slope_time = QtGui.QLabel(self.widget1)
        self.label_slope_time.setObjectName(_fromUtf8("label_slope_time"))
        self.verticalLayout_time_slope.addWidget(self.label_slope_time)
        self.doubleSpinBox_slope_time = QtGui.QDoubleSpinBox(self.widget1)
        self.doubleSpinBox_slope_time.setEnabled(False)
        self.doubleSpinBox_slope_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_slope_time.setMaximum(3600.0)
        self.doubleSpinBox_slope_time.setSingleStep(30.0)
        self.doubleSpinBox_slope_time.setProperty("value", 300.0)
        self.doubleSpinBox_slope_time.setObjectName(_fromUtf8("doubleSpinBox_slope_time"))
        self.verticalLayout_time_slope.addWidget(self.doubleSpinBox_slope_time)
        self.horizontalLayout_timing.addLayout(self.verticalLayout_time_slope)
        self.verticalLayout_time_steady = QtGui.QVBoxLayout()
        self.verticalLayout_time_steady.setMargin(1)
        self.verticalLayout_time_steady.setSpacing(3)
        self.verticalLayout_time_steady.setObjectName(_fromUtf8("verticalLayout_time_steady"))
        self.label_steady_time = QtGui.QLabel(self.widget1)
        self.label_steady_time.setObjectName(_fromUtf8("label_steady_time"))
        self.verticalLayout_time_steady.addWidget(self.label_steady_time)
        self.doubleSpinBox_steady_time = QtGui.QDoubleSpinBox(self.widget1)
        self.doubleSpinBox_steady_time.setEnabled(False)
        self.doubleSpinBox_steady_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_steady_time.setMaximum(3600.0)
        self.doubleSpinBox_steady_time.setSingleStep(30.0)
        self.doubleSpinBox_steady_time.setProperty("value", 120.0)
        self.doubleSpinBox_steady_time.setObjectName(_fromUtf8("doubleSpinBox_steady_time"))
        self.verticalLayout_time_steady.addWidget(self.doubleSpinBox_steady_time)
        self.horizontalLayout_timing.addLayout(self.verticalLayout_time_steady)
        self.verticalLayout_time_move = QtGui.QVBoxLayout()
        self.verticalLayout_time_move.setMargin(1)
        self.verticalLayout_time_move.setSpacing(3)
        self.verticalLayout_time_move.setObjectName(_fromUtf8("verticalLayout_time_move"))
        self.label_move_time = QtGui.QLabel(self.widget1)
        self.label_move_time.setObjectName(_fromUtf8("label_move_time"))
        self.verticalLayout_time_move.addWidget(self.label_move_time)
        self.doubleSpinBox_move_time = QtGui.QDoubleSpinBox(self.widget1)
        self.doubleSpinBox_move_time.setEnabled(False)
        self.doubleSpinBox_move_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_move_time.setMaximum(600.0)
        self.doubleSpinBox_move_time.setSingleStep(5.0)
        self.doubleSpinBox_move_time.setProperty("value", 20.0)
        self.doubleSpinBox_move_time.setObjectName(_fromUtf8("doubleSpinBox_move_time"))
        self.verticalLayout_time_move.addWidget(self.doubleSpinBox_move_time)
        self.horizontalLayout_timing.addLayout(self.verticalLayout_time_move)
        self.widget2 = QtGui.QWidget(Dialog_sequence_gen)
        self.widget2.setGeometry(QtCore.QRect(20, 250, 461, 51))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.horizontalLayout_SPEED = QtGui.QHBoxLayout(self.widget2)
        self.horizontalLayout_SPEED.setObjectName(_fromUtf8("horizontalLayout_SPEED"))
        self.verticalLayout_rpm_min = QtGui.QVBoxLayout()
        self.verticalLayout_rpm_min.setMargin(1)
        self.verticalLayout_rpm_min.setSpacing(3)
        self.verticalLayout_rpm_min.setObjectName(_fromUtf8("verticalLayout_rpm_min"))
        self.label_speed_min = QtGui.QLabel(self.widget2)
        self.label_speed_min.setObjectName(_fromUtf8("label_speed_min"))
        self.verticalLayout_rpm_min.addWidget(self.label_speed_min)
        self.spinBox_rpm_min = QtGui.QSpinBox(self.widget2)
        self.spinBox_rpm_min.setEnabled(False)
        self.spinBox_rpm_min.setFrame(True)
        self.spinBox_rpm_min.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_rpm_min.setMinimum(400)
        self.spinBox_rpm_min.setMaximum(2500)
        self.spinBox_rpm_min.setSingleStep(10)
        self.spinBox_rpm_min.setProperty("value", 1000)
        self.spinBox_rpm_min.setObjectName(_fromUtf8("spinBox_rpm_min"))
        self.verticalLayout_rpm_min.addWidget(self.spinBox_rpm_min)
        self.horizontalLayout_SPEED.addLayout(self.verticalLayout_rpm_min)
        self.verticalLayout_rpm_max = QtGui.QVBoxLayout()
        self.verticalLayout_rpm_max.setMargin(1)
        self.verticalLayout_rpm_max.setSpacing(3)
        self.verticalLayout_rpm_max.setObjectName(_fromUtf8("verticalLayout_rpm_max"))
        self.label_speed_max = QtGui.QLabel(self.widget2)
        self.label_speed_max.setObjectName(_fromUtf8("label_speed_max"))
        self.verticalLayout_rpm_max.addWidget(self.label_speed_max)
        self.spinBox_rpm_max = QtGui.QSpinBox(self.widget2)
        self.spinBox_rpm_max.setEnabled(False)
        self.spinBox_rpm_max.setFrame(True)
        self.spinBox_rpm_max.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_rpm_max.setMinimum(400)
        self.spinBox_rpm_max.setMaximum(2500)
        self.spinBox_rpm_max.setSingleStep(10)
        self.spinBox_rpm_max.setProperty("value", 2000)
        self.spinBox_rpm_max.setObjectName(_fromUtf8("spinBox_rpm_max"))
        self.verticalLayout_rpm_max.addWidget(self.spinBox_rpm_max)
        self.horizontalLayout_SPEED.addLayout(self.verticalLayout_rpm_max)
        self.verticalLayout_rpm_step = QtGui.QVBoxLayout()
        self.verticalLayout_rpm_step.setMargin(1)
        self.verticalLayout_rpm_step.setSpacing(3)
        self.verticalLayout_rpm_step.setObjectName(_fromUtf8("verticalLayout_rpm_step"))
        self.label_speed_step = QtGui.QLabel(self.widget2)
        self.label_speed_step.setObjectName(_fromUtf8("label_speed_step"))
        self.verticalLayout_rpm_step.addWidget(self.label_speed_step)
        self.spinBox_rpm_step = QtGui.QSpinBox(self.widget2)
        self.spinBox_rpm_step.setEnabled(False)
        self.spinBox_rpm_step.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_rpm_step.setMinimum(25)
        self.spinBox_rpm_step.setMaximum(2500)
        self.spinBox_rpm_step.setSingleStep(10)
        self.spinBox_rpm_step.setProperty("value", 200)
        self.spinBox_rpm_step.setObjectName(_fromUtf8("spinBox_rpm_step"))
        self.verticalLayout_rpm_step.addWidget(self.spinBox_rpm_step)
        self.horizontalLayout_SPEED.addLayout(self.verticalLayout_rpm_step)
        self.verticalLayout_rpm_direction = QtGui.QVBoxLayout()
        self.verticalLayout_rpm_direction.setMargin(1)
        self.verticalLayout_rpm_direction.setSpacing(3)
        self.verticalLayout_rpm_direction.setObjectName(_fromUtf8("verticalLayout_rpm_direction"))
        self.label_speed_direction = QtGui.QLabel(self.widget2)
        self.label_speed_direction.setObjectName(_fromUtf8("label_speed_direction"))
        self.verticalLayout_rpm_direction.addWidget(self.label_speed_direction)
        self.horizontalLayout_speed_direction = QtGui.QHBoxLayout()
        self.horizontalLayout_speed_direction.setObjectName(_fromUtf8("horizontalLayout_speed_direction"))
        self.checkBox_rpm_dir_TD = QtGui.QCheckBox(self.widget2)
        self.checkBox_rpm_dir_TD.setEnabled(False)
        self.checkBox_rpm_dir_TD.setAutoExclusive(True)
        self.checkBox_rpm_dir_TD.setObjectName(_fromUtf8("checkBox_rpm_dir_TD"))
        self.horizontalLayout_speed_direction.addWidget(self.checkBox_rpm_dir_TD)
        self.checkBox_rpm_dir_BU = QtGui.QCheckBox(self.widget2)
        self.checkBox_rpm_dir_BU.setEnabled(False)
        self.checkBox_rpm_dir_BU.setChecked(True)
        self.checkBox_rpm_dir_BU.setAutoExclusive(True)
        self.checkBox_rpm_dir_BU.setObjectName(_fromUtf8("checkBox_rpm_dir_BU"))
        self.horizontalLayout_speed_direction.addWidget(self.checkBox_rpm_dir_BU)
        self.verticalLayout_rpm_direction.addLayout(self.horizontalLayout_speed_direction)
        self.horizontalLayout_SPEED.addLayout(self.verticalLayout_rpm_direction)
        self.buttonBox.raise_()
        self.layoutWidget.raise_()
        self.lineEdit_gen_seq_name.raise_()
        self.label_gen_seq_name.raise_()
        self.spinBox_rpm_min.raise_()
        self.label_speed_min.raise_()
        self.spinBox_rpm_max.raise_()
        self.label_speed_max.raise_()
        self.label_speed_step.raise_()
        self.spinBox_rpm_step.raise_()
        self.checkBox_rpm_dir_TD.raise_()
        self.label_speed_direction.raise_()
        self.checkBox_rpm_dir_BU.raise_()
        self.listWidget_types.raise_()
        self.layoutWidget_4.raise_()

        self.retranslateUi(Dialog_sequence_gen)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog_sequence_gen.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog_sequence_gen.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_sequence_gen)

    def retranslateUi(self, Dialog_sequence_gen):
        Dialog_sequence_gen.setWindowTitle(_translate("Dialog_sequence_gen", "Dialog", None))
        self.label_seq_gen.setText(_translate("Dialog_sequence_gen", "Choose the type of sequence to be generated", None))
        self.pushButton_open_existing_seq.setText(_translate("Dialog_sequence_gen", "Open existing sequence for edit", None))
        self.pushButton_reset_seq_gen.setText(_translate("Dialog_sequence_gen", "Reset all choice (and input)", None))
        self.label_load_min.setText(_translate("Dialog_sequence_gen", "LOAD min", None))
        self.label_load_max.setText(_translate("Dialog_sequence_gen", "LOAD max", None))
        self.label_load_step.setText(_translate("Dialog_sequence_gen", "LOAD step", None))
        self.label_load_direction.setText(_translate("Dialog_sequence_gen", "Sequence or slope direction", None))
        self.checkBox_load_dir_TD.setText(_translate("Dialog_sequence_gen", "Top>Down", None))
        self.checkBox_load_dir_BU.setText(_translate("Dialog_sequence_gen", "Bottom>Up", None))
        self.label_gen_seq_name.setToolTip(_translate("Dialog_sequence_gen", "Insert the name you want assign to the sequence to be generated", None))
        self.label_gen_seq_name.setText(_translate("Dialog_sequence_gen", "Name of the sequence to be generated", None))
        self.lineEdit_gen_seq_name.setText(_translate("Dialog_sequence_gen", "SeqType", None))
        self.label_slope_time.setText(_translate("Dialog_sequence_gen", "Slope time [s]", None))
        self.label_steady_time.setText(_translate("Dialog_sequence_gen", "Steady time [s]", None))
        self.label_move_time.setText(_translate("Dialog_sequence_gen", "Move time [s]", None))
        self.label_speed_min.setText(_translate("Dialog_sequence_gen", "RPM min", None))
        self.label_speed_max.setText(_translate("Dialog_sequence_gen", "RPM max", None))
        self.label_speed_step.setText(_translate("Dialog_sequence_gen", "RPM step", None))
        self.label_speed_direction.setText(_translate("Dialog_sequence_gen", "Sequence or slope direction", None))
        self.checkBox_rpm_dir_TD.setText(_translate("Dialog_sequence_gen", "Top>Down", None))
        self.checkBox_rpm_dir_BU.setText(_translate("Dialog_sequence_gen", "Bottom>Up", None))

